# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e98945aee9b26e30096b65166dacea804ea422e6ad0fa8c185638128b6936a0708c88b21758e4a26500b6d6803c393b8714952d6f7af6f3d982c3e24a7fcb7

test:
  secret_key_base: 7012fdd671f9f18df7e66383f1f8d538b3cac3fdf2a9f4153d2719d9d2533d20f76dcd7a7ff608458b1cd522fee4abe65ac4a36de04f65ed7aa5abe7de28264d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
